logging.level.org.springframework.security=DEBUG
#App properties
spring.config.import=optional:file:.env[.properties]
app.jwt-secret=${JWT_SECRET_KEY}
#using encrypted password (via sha 256)
app-jwt-expiration-milliseconds=${JWT_EXPIRATION_MILLISECONDS}
spring.profiles.active=dev

